### PR TITLE
fix(owner filter): Pass owner down through list methods PE-645

### LINKED ISSUE #124: STILL not properly filtering by drive owner address
`ardrive list-drive -d bfe2ff28-6efe-4a00-8d1e-ad5f091e28a6`

Do I have to add malware to your drives for you to start taking security seriously?

### PR DESCRIPTION
**Pull request by fedellen**
This PR passes the derived drive owner down into the list methods, which will filter the `list-drive` and `list-folder` commands by the original drive owner.

Fixes #124

### CODE REVIEW

**Review by jdaev — APPROVED** [review]
LGTM

File: src/arfsdao.ts [hunk 1]
```diff
@@ -691,6 +692,7 @@ export class ArFSDAO extends ArFSDAOAnonymous {
 	async getAllFoldersOfPrivateDrive(
```
Comment (arielmelendez) [inline src/arfsdao.ts:692]: Though my type safety branches will prevent issues here, I'd make this a deconstructed object parameter list.

File: src/arfsdao_anonymous.ts [hunk 2]
```diff
@@ -171,24 +173,31 @@ export class ArFSDAOAnonymous extends ArFSDAOType {
 		return latestRevisionsOnly ? allFiles.filter(latestRevisionFilter) : allFiles;
 	}
 
-	async getAllFoldersOfPublicDrive(driveId: DriveID, latestRevisionsOnly = false): Promise<ArFSPublicFolder[]> {
+	async getAllFoldersOfPublicDrive(
```
Comment (arielmelendez) [inline src/arfsdao_anonymous.ts:176]: Consider deconstructing

File: src/arfsdao_anonymous.ts [hunk 3]
```diff
@@ -171,24 +173,31 @@ export class ArFSDAOAnonymous extends ArFSDAOType {
...
+		driveId: DriveID,
+		owner: ArweaveAddress,
+		latestRevisionsOnly = false
+	): Promise<ArFSPublicFolder[]> {
 		let cursor = '';
 		let hasNextPage = true;
 		const allFolders: ArFSPublicFolder[] = [];
 
 		while (hasNextPage) {
+			console.log('owner in getAll', owner);
```
Comment (arielmelendez) [inline src/arfsdao_anonymous.ts:186]: Remove this

**Review by arielmelendez — CHANGES_REQUESTED** [review]
One console log that needs to be removed and some suggestions for parameters.

File: src/arfsdao_anonymous.ts (hunk 3 above)
Comment (fedellen) [reply src/arfsdao_anonymous.ts]: Oops, thanks! 

f516798

File: src/arfsdao.ts (hunk 1 above)
Comment (fedellen) [reply src/arfsdao.ts]: There it is: 8198d1c

**Review by arielmelendez — APPROVED** [review]
